### ISSUE TITLE
brew install khiva

### ISSUE THREAD

**Issue by ankane** [shapelets/khiva#158]
Hi, thanks for this great library! Just wanted to let you know it's now available on Homebrew, so Mac users can install it with:

```sh
brew install khiva
```

Homebrew installs all dependencies and precompiles the library for each version of macOS, so installation is really quick and easy. 🎉 

Ref: https://github.com/Homebrew/homebrew-core/pull/67078

**Comment by justoruiz** [comment]
Awesome!!  👍

This is truly appreciated and we are thankful for you contribution!!
