### ISSUE TITLE
Ruby bindings

### ISSUE THREAD

**Issue by ankane** [shapelets/khiva#159]
Hi, also wanted to let you know there are now [Ruby bindings](https://github.com/ankane/khiva-ruby) for Khiva. It's modeled after the Python bindings (with some minor changes to make it more Ruby-like). The C API was really nice to use and easy to follow.

If you have any feedback, feel free to let me know here or create an issue in the project. Thanks!

**Comment by avilchess** [comment]
Hi Andrew, first at all thanks for these two fantastic contributions. The brew package will ease the installation process for Mac users massively. Regarding the Ruby binding, it seems to be really nice (I'm not a Ruby expert though). I'm adding a new section, listing the available bindings, to the REAME.md file (https://github.com/shapelets/khiva/pull/160). We are thrilled to see more people contributing to the project. Stay tuned we are planning to keep adding more functions in the next months.

**Comment by ankane** [comment]
Great, thanks @avilchess!
