### ISSUE TITLE
Features::localMaximals() function bug

### ISSUE THREAD

**Issue by Nexxel** [shapelets/khiva#97]
**Describe the bug**
That function produces a OSError tested in Python:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Python37\lib\site-packages\khiva\features.py", line 607, in local_maximals
    ctypes.pointer(b))
OSError: [WinError -529697949] Windows Error 0xe06d7363

**To Reproduce**
import khiva as kv
import numpy as np
local_maximals_result = kv.local_maximals(kv.Array(data=[0.0, 4.0, 3.0, 5.0, 4.0, 1.0, 0.0, 4.0])).to_numpy()

**Expected behavior**
numpy array of [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
**Environment information:**

- OS: Windows
- Version 10
- Khiva dependencies versions [e.g. ArrayFire 3.6.2, Boost 1.66.0]

**Comment by raulbocanegra** [comment]
Fixed on #153
