### ISSUE TITLE
@param index not in bindings/include/matrix find_best_n_discords function

### ISSUE THREAD

**Issue by Nexxel** [shapelets/khiva#98]
**Describe the bug**
In the documentation of find_best_n_discords function there is a @param that does not include the number of the param

**Expected behavior**
/**
         * @brief Primitive of the findBestNDiscords function.
         *
         * @param profile The matrix profile containing the minimum distance of each
         * subsequence
         * @param index The matrix profile index containing the index of the most similar
         * subsequence
         * @param length_profile Length of the matrix profile
         * @param m Subsequence length value used to calculate the input matrix profile.
         * @param n Number of discords to extract
         * @param discord_distances The distance of the best N discords
         * @param discord_indices The indices of the best N discords
         * @param subsequence_indices The indices of the query sequences that produced
         * the "N" bigger discords.
         * @param self_join Indicates whether the input profile comes from a self join operation or not. It determines
         * whether the mirror similar region is included in the output or not.
         */

**Comment by raulbocanegra** [comment]
Fixed on #153
