### ISSUE TITLE
@param that are not parameters of the bindings/c/include znorm function

### ISSUE THREAD

**Issue by Nexxel** [shapelets/khiva#99]
**Describe the bug**
In the documentation it appears as tss_l and tss_n as parameters of the znorm functions and they are not parameters

**Expected behavior**
 /**
         * @brief Calculates a new set of times series with zero mean and standard deviation one.
         *
         * @param tss Time series concatenated in a single row.
         * @param epsilon Minimum standard deviation to consider. It acts as a gatekeeper for
         * those time series that may be constant or near constant.
         * @param result Array with the same dimensions as tss where the time series have been
         * adjusted for zero mean and one as standard deviation.
         */
        [DllImport(DLLLibrary.khivaPath, CallingConvention = CallingConvention.Cdecl)]
        public extern static void znorm([In] ref IntPtr tss, [In] ref double epsilon, [Out] out IntPtr result);

**Comment by raulbocanegra** [comment]
Fixed on #153
